### PR TITLE
Use Twitter OG tags if no Twitter credentials are configured

### LINKED ISSUE #499: Twitter: Use OG resolver by default
Since the Twitter API is now absurdly expensive, it is reasonable to assume that most hosters do not want to pay for an API key. Therefore, Twitter links should be handled by the Open Graph link resolver by default.

### PR DESCRIPTION
**Pull request by M4tthewDE**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Appends "(bot)" to User-Agent so that the default resolver can fetch OpenGraph tags for twitter links.
I don't like how this identifies twitter links, but it's the best I could come up with on the spot.

Note that the default resolver is only used if no Twitter token is specified in the config.

Closes #499

### CODE REVIEW

**Comment by KararTY** [comment]
Had to look for a bit since I remember paj saying something:
image
> the user-agent must only be added to the twitter requests

**Comment by KararTY** [comment]
Also if I'm not mistaken, https://github.com/Chatterino/api/pull/510 is also trying to solve the same underlying issue - The fact Twitter embeds don't work.

I don't know if there has been a discussion whether we'd go that route or this route with OG tags.

**Comment by M4tthewDE** [comment]
I would consider falling back to OG tags by default to be desirable despite the other PR, since the API used there is unofficial.

**Review by pajlada — APPROVED** [review]
Thank you!

**Pull request merged**
