### PR TITLE
Use Normalized title instead of Display title from Wikipedia API

### LINKED ISSUE #106: Wikipedia title should use titles.Normalized instead of titles.Display
When querying the Wikipedia page summary API for an article we get 3 different title keys:
canonical, normalized, and display.
 we currently use display, which seems fine for most cases but for pages like https://en.wikipedia.org/wiki/Test_(2013_film) with Display we get the italized version which shows up as <i>Test</i> in the tooltip right now.

 We should probably move to the "normalized" key instead

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

Fixes #106

# Description

### CODE REVIEW

**Comment by pajlada** [comment]
Tested this on stream on a local version of the link resolver

**Review by zneix — APPROVED** [review]
Tested on my end as well, good stuff

**Comment by leon-richardt** [comment]
How does this behave with https://en.wikipedia.org/wiki/IOS_13 for example? Would test myself but currently not able to

**Comment by zneix** [comment]
master:
hey mm

this PR:
hey leon lole

**Review by leon-richardt — APPROVED** [review]

**Pull request merged**
