### PR TITLE
Block direct requests to private IPs

### LINKED ISSUE #480: Block private network requests
Currently, the API can make requests to the local network (e.g. 192.168.0.1)

We should block this

See https://datatracker.ietf.org/doc/html/rfc1918

### PR DESCRIPTION
**Pull request by M4tthewDE**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

### CODE REVIEW

**Review by KararTY — COMMENTED** [review]
Nice, TIL https://pkg.go.dev/net#IP.IsPrivate

**Comment by Mm2PL** [comment]
This will still resolve hosts pointed to by DNS records. For example if we'd have an A record saying `localhost.example.com -> 127.0.0.1`, this won't ignore `127.0.0.1`.

**Comment by M4tthewDE** [comment]
That should be handled via the ignored hosts imo. It might be worthwhile to add a config option for ignored hosts, since as of now they can only be added by patching the source.

**Comment by pajlada** [comment]
Go's HTTP client has a way to customize parts of the transport layer, see https://pkg.go.dev/net/http#Client and https://pkg.go.dev/net/http#RoundTripper - with this we should be able to intercept the request after the domain resolving has happened & stop it mid-transit instead
Happy to discuss if this feels like a bad idea

**Comment by M4tthewDE** [comment]
I was not able to find a way to intercept requests after the domain resolving. If this is not feasible, we could instead make the ignored hosts configurable and maybe add common hosts (e.g. localhost) as a default entry.

**Review by pajlada — APPROVED** [review]
This is a good first effort, so I will go ahead and merge this in as-is, but I won't close #480 
Thanks!

**Pull request merged**
