### PR TITLE
make link_resolver respect robots.txt

### PR DESCRIPTION
**Pull request by the-vesuvius**
My attempt to fix this [issue](https://github.com/Chatterino/api/issues/13).
Not sure if my solution is ok (I'm new to golang) so feedback would be appreciated :)

### CODE REVIEW

**Comment by zneix** [comment]
Awesome work! I really like this, however I get a feeling that general message for forbidden hosts (`The url is forbidden by robots.txt`) might be sometimes "too nerdy" for less advanced users that have no idea how works or what is robots.txt.  
I suggest to change it a bit, so everyone will understand that preview is blocked by a remote site, for example: `This site blocks link previews.`.

**Comment by StefanStas** [comment]
@zneix Thanks for the feedback

_>> I suggest to change it a bit, so everyone will understand that preview is blocked by a remote site, for example: This site blocks link previews._
yes, I agree. Fixed this

_>>Btw, you can include "Closes #13" in your comment, so the related issue will be closed automatically upon merging :)_
ok, didn't know this, thanks :)

**Comment by zneix** [comment]
On a second thought, we should think twice before merging this PR. I just realized how many sites have all User-Agents disallowed, thus that's going to "break" a lot of link previews and many Chatterino users might get mad/upset about it. I realize that this will just reject a feature that should be implemented, but it's going to heavily limit potential of chatterino's API.

Short list of sites for which previews are going to break:
- []()
- []()
- []()
- []()

**Comment by StefanStas** [comment]
I guess in this case this PR shouldn't get merged
Should I close it?

**Comment by alazymeme** [comment]
> Should I close it?

No, just wait. pajlada/fourtf might suggest an alternate way of fixing this.

**Comment by zneix** [comment]
Yeah, I just pointed out that this might cause some issues, but we should wait for maintainers to decide.

**Comment by the-vesuvius** [comment]
ok, got you

**Comment by pajlada** [comment]
Thanks a lot for the contribution - I will leave this hanging a bit while I give it more thought.

**Comment by alazymeme** [comment]
@pajlada Still thinking? 🤔

**Comment by the-vesuvius** [comment]
I've made the requested change however I agree with RAnders00 about closing this PR

**Comment by pajlada** [comment]
Thanks for your work on the PR @the-vesuvius as expected we will not be pursuing this. I appreciate the experimentation and discussion your PR has spawned though!

**Pull request closed without merging**
